# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170325_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
