# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170325_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='userid',
            new_name='username',
        ),
    ]
