# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('type', models.IntegerField(choices=[(1, 'General message and system related logs'), (2, 'Authentication Logs'), (3, 'Login Records'), (4, 'MySQL database server log file'), (5, 'Kernal Logs'), (6, 'System boot Log'), (7, 'dpkg'), (8, 'Mail Server Logs')])),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=40)),
                ('ram_description', models.CharField(max_length=50)),
                ('ram_capacity', models.IntegerField()),
                ('disk_capacity', models.IntegerField()),
                ('disk_used_amount', models.IntegerField()),
                ('disk_description', models.CharField(max_length=50)),
                ('motherboard_description', models.CharField(max_length=50)),
                ('cpu_name', models.CharField(max_length=50)),
                ('cpu_cores', models.CharField(max_length=50)),
                ('cpu_clock_speed', models.IntegerField()),
                ('os_name', models.CharField(max_length=20)),
                ('os_version', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MachineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_messages', to='info.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Keyboard'), (2, 'Mouse'), (3, 'Speaker')])),
                ('presence', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals', to='info.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_machine', to='info.Machine')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user', to='info.MachineUser')),
            ],
        ),
        migrations.CreateModel(
            name='Softwaresinstalled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('update_available', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares_installed', to='info.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='UsersActiveOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_machines', to='info.Machine')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='info.MachineUser')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_session', to='info.Session'),
        ),
        migrations.AddField(
            model_name='messages',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='info.MachineUser'),
        ),
        migrations.AddField(
            model_name='logs',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinelogs', to='info.Machine'),
        ),
        migrations.AddField(
            model_name='logs',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_session', to='info.Session'),
        ),
        migrations.AddField(
            model_name='logs',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlogs', to='info.MachineUser'),
        ),
    ]
